// board-svg 유틸 단위 테스트.
import { describe, it, expect } from "vitest";
import { parseBoardCodeBlock } from "../lib/board-svg";

describe("parseBoardCodeBlock", () => {
  it("parses size, position rows, caption", () => {
    const src = `size: 9
position: |
  .........
  ....B....
  ...WB....
  ....W....
  .........
  .........
  .........
  .........
  .........
caption: 축의 시작`;
    const spec = parseBoardCodeBlock(src);
    expect(spec.size).toBe(9);
    expect(spec.position).toHaveLength(9);
    expect(spec.position[1]).toBe("....B....");
    expect(spec.position[2]).toBe("...WB....");
    expect(spec.caption).toBe("축의 시작");
  });

  it("defaults size to 19 when missing", () => {
    const lines = ["position: |"].concat(Array(19).fill("  ...................")).join("\n");
    const spec = parseBoardCodeBlock(lines);
    expect(spec.size).toBe(19);
    expect(spec.position).toHaveLength(19);
  });

  it("pads short position rows with dots", () => {
    const src = `size: 9
position: |
  ....B
  .........
  .........
  .........
  .........
  .........
  .........
  .........
  .........`;
    const spec = parseBoardCodeBlock(src);
    expect(spec.position[0]).toBe("....B....");
  });

  it("pads missing position rows with empty rows", () => {
    const src = `size: 9
position: |
  ....B....
  ....W....`;
    const spec = parseBoardCodeBlock(src);
    expect(spec.position).toHaveLength(9);
    expect(spec.position[2]).toBe(".........");
    expect(spec.position[8]).toBe(".........");
  });

  it("replaces invalid characters with dot", () => {
    const src = `size: 9
position: |
  X.X......
  .........
  .........
  .........
  .........
  .........
  .........
  .........
  .........`;
    const spec = parseBoardCodeBlock(src);
    expect(spec.position[0]).toBe(".........");
  });

  it("omits caption when not present", () => {
    const src = `size: 9
position: |
  .........
  .........
  .........
  .........
  .........
  .........
  .........
  .........
  .........`;
    const spec = parseBoardCodeBlock(src);
    expect(spec.caption).toBeUndefined();
  });
});
